### PR TITLE
Namespace issues: #define BLACK conflicts - fixes #146

### LINKED ISSUE #146: Namespace issues:  #define BLACK conflicts
The unadorned use of BLACK, WHITE and INVERSE cause hard to debug issues when they are defined or declared by some other sketch construct.

- Board:  SSD1306

- List the steps to reproduce the problem below

#define BLACK 0xFF

#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>

enum Colors  {WHITE, GREEN, BLUE};

Compile will complain variously about badness that happens when "BLACK" is converted to "0" everywhere:

...Arduino/libraries/Adafruit_SSD1306/Adafruit_SSD1306.h:51:15: error: expected identifier before numeric constant
 #define BLACK 0
               ^

(which is really #define 0 0 under the cpp hood, but the Arduino IDE won't tell you that...)

Suggested fix:

At a minimum, an #if defined(BLACK)/#error "the name BLACK has been redefined" wrapper might help,
though it doesn't fix the problem or address the case of a non-preprocessor usage:
enum Colors {BLACK, WHITE, GREEN...}

Alternatively, #define COLOR_BLACK 0   might be cleaner, though with a bigger documentation change footprint

Best would to make these  class scoped const's inside the class Adafruit_SSD1306

### PR DESCRIPTION
**Pull request by plocher**
Commented out #defines for BLACK, WHITE, INVERSE
Created enum in Adafruit_SSD1306
      enum SSD1306_Colors { BLACK=0, WHITE=1, INVERSE=2 };
Modified implementation to use the enums instead of defines
Updated sketches in examples directory
Tested with several of my existing projects

This is an incompatible change!  
User's sketch code will need to change 
uses of, for example, WHITE change to Adafruit_SSD1306::WHITE

I chose to NOT leave behind compatibility defines of the form
#define BLACK Adafruit_SSD1306::BLACK
since they would still cause the original problem :-)
  -John

### CODE REVIEW

File: Adafruit_SSD1306.h [hunk 1]
```diff
@@ -130,6 +130,8 @@ class Adafruit_SSD1306 : public Adafruit_GFX {
 
   ~Adafruit_SSD1306(void);
 
+  enum SSD1306_Colors { BLACK=0, WHITE=1, INVERSE=2 };
```
Comment (BillyDonahue) [inline Adafruit_SSD1306.h]: If I'm following along correctly, the reason for this change was that another module used a `#define BLACK 0`. Well if that situation arises again, such a macro definition would still affect this header the same way and the problem remains: you're still using the token `BLACK`.

If you're going to bring these into C++ from the preprocessor, which is a good idea, maybe give them names that won't conflict with the macro all-caps convention?

Maybe change to Black, White, Inverse.

Also if your enum is nested inside a class called Adafruit_SSD1306, you shouldn't have to say SSD1306 again in the name: `enum Adafruit_SSD1306::SSD1306_Colors`. Just `enum Adafruit_SSD1306::Colors` seems better.

**Comment by BillyDonahue** [comment]
You haven't resolved the original problem if you're still using the C++ tokens BLACK, WHITE, etc. These will be replaced by the preprocessor as they're encountered. The preprocessor doesn't heed the C++ scope `::` operator.

Your enum definition might still compile if the OtherHeader.h appears after Adafruit_SSD1306.h in the #include list.

But further down in the user's C++ code, the sequence `Adafruit_SSD1306::BLACK` will not be referring to an enum value. What the compiler will see is something like `Adafruit_SSD1306::0`, which is an error.

Create a test that simulates the one you're trying to fix and seeing if your solution fixes it.
Godbolt is good for quick prototypes.  The -E compiler flag here doesn't compile the code. It just preprocesses it so you can see how the preprocessor works.
https://gcc.godbolt.org/z/BZgpwg

**Comment by plocher** [comment]
My test was the inverse - The pull request is to make sure the Adafruit lib doesn't tromp on my sketch's namespace.

If I have a sketch with
```
#include "Adafruit_SSD1306.h"  
#define BLACK 0xFF // Poor example, as this will still break the Adafruit lib API if I use the token later...
enum MyColors {RED, BLUE, BLACK, BROWN};
```
my sketch's #define BLACK 0xFF or enum { ... BLACK ...} (i.e., anywhere I use those tokens...) will all fail with useless compiler errors.  This fixes **that** problem ;-)  

The remaining task is to protect the Adafruit lib from other people's defines.  The fix there is to NOT USE #defines in C++ because, as you point out, #defines are a global menace however they are used.

I'd happily change enum {BLACK...}   to enum { SSD1306_BLACK...} to make it _less likely_ to have a conflict; changing it to Black (i.e., just a letter case change) feels like a halfway punt that still may cause issues...

I'll defer to y'all.

**Comment by plocher** [comment]
re: the Travis failures 

These are an expected side effect of this change.

**Comment by ladyada** [comment]
ok thanx!
first up, do examples still work with original `BLACK` and `WHITE` text so older projects continue to work?

**Comment by plocher** [comment]
Update:  Based on comments asking for simplicity and a desire to be harmless to the installed base, I backed out the enum approach and redid things using the header file's existing #define design pattern:

   * I created new #defines for SSD1306_BLACK, SSD1306_WHITE and SSD1306_INVERSE 
   * I kept the old #defines for BLACK, WHITE and INVERSE for backwards compatibility
   * These compatibility macros do a text -to- text swap that won't trigger odd compiler messages caused by "#define 0 0" and the like...
   * I added a new opt-out mechanism that won't define these compatibility macros:
     * ``` #define NO_ADAFRUIT_SSD1306_COLOR_COMPATIBILITY)```

```
/// The following "raw" color names are kept for backwards client compatability
/// They can be disabled by predefining this macro before including the Adafruit header
/// client code will then need to be modified to use the scoped enum values directly
#ifndef NO_ADAFRUIT_SSD1306_COLOR_COMPATIBILITY
#define BLACK                     SSD1306_BLACK    ///< Draw 'off' pixels
#define WHITE                     SSD1306_WHITE    ///< Draw 'on' pixels
#define INVERSE                   SSD1306_INVERSE  ///< Invert pixels
#endif
        /// fit into the SSD1306_ naming scheme
#define SSD1306_BLACK               0    ///< Draw 'off' pixels
#define SSD1306_WHITE               1    ///< Draw 'on' pixels
#define SSD1306_INVERSE             2    ///< Invert pixels
```

For my use case (protecting my sketch tokens from Adafruit_SSD1306.h's define damage), it is sufficient to #define NO_ADAFRUIT_SSD1306_COLOR_COMPATIBILITY before including the header.  

The library (and examples) now all use the scoped defines (SSD1306_BLACK...) and so should be somewhat isolated from redefinitions of the unqualified BLACK, WHITE and INVERSE compatibility macros, though there still will be unavoidable sketch errors when multiple parties try to each #define the same tokens to different values in the same sketch...

  -John

**Comment by ladyada** [comment]
thanks! @makermelissa please check it out & test at your convenience

File: Adafruit_SSD1306.cpp [hunk 2]
```diff
@@ -592,7 +592,7 @@ boolean Adafruit_SSD1306::begin(uint8_t vcs, uint8_t addr, boolean reset,
     @param  y
             Row of display -- 0 at top to (screen height -1) at bottom.
     @param  color
-            Pixel color, one of: BLACK, WHITE or INVERT.
+            Pixel color, one of: SSD1306_BLACK, _WHITE or _INVERT.
```
Comment (makermelissa) [inline Adafruit_SSD1306.cpp]: The _WHITE and _INVERT should be updated to match the new names SSD1306_WHITE and SSD1306_WHITE. I'm guessing this was just a typo.

File: Adafruit_SSD1306.cpp [hunk 3]
```diff
@@ -644,7 +644,7 @@ void Adafruit_SSD1306::clearDisplay(void) {
     @param  w
             Width of line, in pixels.
     @param  color
-            Line color, one of: BLACK, WHITE or INVERT.
+            Line color, one of: SSD1306_BLACK, _WHITE or _INVERT.
```
Comment (makermelissa) [inline Adafruit_SSD1306.cpp]: Same here.

File: Adafruit_SSD1306.cpp [hunk 4]
```diff
@@ -713,7 +713,7 @@ void Adafruit_SSD1306::drawFastHLineInternal(
     @param  h
             Height of line, in pixels.
     @param  color
-            Line color, one of: BLACK, WHITE or INVERT.
+            Line color, one of: SSD1306_BLACK, _WHITE or _INVERT.
```
Comment (makermelissa) [inline Adafruit_SSD1306.cpp]: and here

Comment (plocher) [reply Adafruit_SSD1306.cpp]: > ... took too long...

me too...
Updated doc strings, ready for you again

**Comment by plocher** [comment]
Is this waiting for anything more from me? - i.e., did I not push the right buttons on GitHub when I added Melissa's requested changes?
